# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: descheduler
serviceType: managed

image:
  registry: quay.io
  name: giantswarm/descheduler
  tag: v0.21.0

schedule: "*/5 * * * *"

deschedulerPolicy:
  # maxNoOfPodsToEvictPerNode: 10
  # maxNoOfPodsToEvictPerNamespace: 10
  # ignorePvcPods: true
  # evictLocalStoragePods: true
  strategies:
    RemoveDuplicates:
      enabled: true
    RemovePodsViolatingNodeTaints:
      enabled: true
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
    LowNodeUtilization:
      enabled: true
      params:
        nodeResourceUtilizationThresholds:
          thresholds:
            cpu: 20
            memory: 20
            pods: 20
          targetThresholds:
            cpu: 50
            memory: 50
            pods: 50

resources:
  requests:
    cpu: 500m
    memory: 256Mi

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1
